sudo: false
language: haskell
ghc:
  - 7.8
install:
  - cabal configure --enable-tests -ghc-options=-Werror
  - cabal build
script: cabal test --show-details=always --test-option=--color --test-option=always
